<?php

declare(strict_types=1);

namespace Semitexa\Core\Support;

use Composer\InstalledVersions;
use Semitexa\Core\Environment;

/**
 * Which Semitexa release is actually running.
 *
 * Answered from `semitexa/core`, because that is the one package every
 * Semitexa application installs and the one whose tag moves with the
 * framework itself. A deployment can override the answer with
 * `SEMITEXA_RELEASE_VERSION` when it wants to publish a distribution
 * version of its own instead.
 *
 * Only a real release ever comes back. A working tree resolves core as
 * `dev-develop` or a path repo, and printing that in a page footer would
 * advertise a version nobody can install; `null` means "no release to
 * name" and callers are expected to omit the line entirely.
 *
 * Static and memoised like {@see ProjectRoot} so a Twig extension can ask
 * without the container having to hand it a collaborator first.
 */
class FrameworkVersion
{
    private const PACKAGE = 'semitexa/core';

    /**
     * The release format the estate tags with: `YYYY.MM.DD.HHMM`, optionally
     * carrying a pre-release suffix.
     */
    private const RELEASE_PATTERN = '/^\d{4}\.\d{2}\.\d{2}\.\d{4}(?:-(?:alpha|beta|rc)\.\d+)?$/';

    private static ?string $version = null;

    private static bool $resolved = false;

    public static function current(): ?string
    {
        if (self::$resolved) {
            return self::$version;
        }

        self::$resolved = true;
        self::$version = self::release((string) (Environment::getEnvValue('SEMITEXA_RELEASE_VERSION', '') ?? ''))
            ?? self::installed();

        return self::$version;
    }

    /**
     * Drop the memoised answer. For tests that move the environment under it.
     */
    public static function reset(): void
    {
        self::$version = null;
        self::$resolved = false;
    }

    private static function installed(): ?string
    {
        // Absent when the autoloader was not generated by Composer 2 — the
        // class is guarded rather than required so core keeps working in a
        // hand-wired build.
        if (!class_exists(InstalledVersions::class) || !InstalledVersions::isInstalled(self::PACKAGE)) {
            return null;
        }

        return self::release((string) (InstalledVersions::getPrettyVersion(self::PACKAGE) ?? ''));
    }

    private static function release(string $candidate): ?string
    {
        $candidate = ltrim(trim($candidate), 'v');

        return preg_match(self::RELEASE_PATTERN, $candidate) === 1 ? $candidate : null;
    }
}
