<?php

declare(strict_types=1);

namespace Semitexa\Core\Tests\Unit\Container;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Semitexa\Core\Attribute\InjectAsFactory;
use Semitexa\Core\Attribute\SatisfiesServiceContract;
use Semitexa\Core\Container\BuildPhase\BuildContext;
use Semitexa\Core\Container\BuildPhase\FactoryBuildPhase;
use Semitexa\Core\Container\BuildPhase\ValidationPhase;
use Semitexa\Core\Container\ContractFactory;
use Semitexa\Core\Container\Exception\ContainerBuildException;
use Semitexa\Core\Container\Exception\InjectionException;
use Semitexa\Core\Container\GraphBuilder;
use Semitexa\Core\Container\InjectionAnalyzer;
use Semitexa\Core\Container\Store\InjectionMap;
use Semitexa\Core\Container\Store\InstanceStore;
use Semitexa\Core\Container\Store\TypeMap;
use Semitexa\Core\Contract\ContractFactoryInterface;
use Semitexa\Core\Registry\RegistryContractResolverGenerator;
use Semitexa\Core\Support\ProjectRoot;
use Semitexa\Core\Tests\Support\StaticState;

interface BootFactoryChannel
{
}

enum BootFactoryChannelKind: string
{
    case Mail = 'mail';
    case Sms = 'sms';
}

/** The documented shape: get() takes the contract's own enum. */
interface FactoryBootFactoryChannel
{
    public function getDefault(): BootFactoryChannel;

    public function get(BootFactoryChannelKind $key): BootFactoryChannel;

    /** @return list<BootFactoryChannelKind> */
    public function keys(): array;
}

#[SatisfiesServiceContract(of: BootFactoryChannel::class, factoryKey: BootFactoryChannelKind::Mail)]
final class BootFactoryMailChannel implements BootFactoryChannel
{
}

#[SatisfiesServiceContract(of: BootFactoryChannel::class, factoryKey: BootFactoryChannelKind::Sms)]
final class BootFactorySmsChannel implements BootFactoryChannel
{
}

final class BootFactoryConsumer
{
    #[InjectAsFactory]
    protected FactoryBootFactoryChannel $channels;

    public function channels(): FactoryBootFactoryChannel
    {
        return $this->channels;
    }
}

/** Typed as the generic factory (vendor docs di/factory.md): names its contract via `of`. */
final class GenericBootFactoryConsumer
{
    #[InjectAsFactory(of: BootFactoryChannel::class)]
    protected ContractFactory $channels;

    public function channels(): ContractFactory
    {
        return $this->channels;
    }
}

final class GenericInterfaceBootFactoryConsumer
{
    #[InjectAsFactory(of: BootFactoryChannel::class)]
    protected ContractFactoryInterface $channels;

    public function channels(): ContractFactoryInterface
    {
        return $this->channels;
    }
}

final class GenericBootFactoryConsumerWithoutContract
{
    #[InjectAsFactory]
    protected ContractFactory $channels;
}

/** A contract whose factory class was never generated. */
interface UngeneratedFactoryChannel
{
}

interface FactoryUngeneratedFactoryChannel
{
    public function get(BootFactoryChannelKind $key): UngeneratedFactoryChannel;
}

final class UngeneratedMailChannel implements UngeneratedFactoryChannel
{
}

final class UngeneratedSmsChannel implements UngeneratedFactoryChannel
{
}

final class UngeneratedFactoryConsumer
{
    protected FactoryUngeneratedFactoryChannel $channels;
}

/**
 * #[InjectAsFactory] properties are typed as the contract's Factory* interface.
 * The container used to hand out its generic ContractFactory, which cannot
 * implement that interface (get() takes the concrete enum), so the assignment
 * threw TypeError. It now wraps the generic factory in the class generated by
 * registry:sync:contracts, and fails boot with a pointer to that command when
 * the class has not been generated.
 */
final class InjectAsFactoryAtBootTest extends TestCase
{
    private static string $root;

    public static function setUpBeforeClass(): void
    {
        $previousCwd = getcwd();
        $projectRootState = StaticState::snapshot(ProjectRoot::class);
        self::$root = sys_get_temp_dir() . '/semitexa-factory-' . bin2hex(random_bytes(6));
        mkdir(self::$root . '/src/modules', 0777, true);
        file_put_contents(self::$root . '/composer.json', '{}');
        chdir(self::$root);
        ProjectRoot::reset();
        try {
            $generated = RegistryContractResolverGenerator::generateAllFactories(self::contractDetails());
        } finally {
            if ($previousCwd !== false) {
                chdir($previousCwd);
            }
            StaticState::restore($projectRootState);
        }
        self::assertSame([[
            'factoryInterface' => FactoryBootFactoryChannel::class,
            'factoryClass' => 'App\\Registry\\Contracts\\BootFactoryChannelFactory',
        ]], $generated);
        require_once self::$root . '/src/registry/Contracts/BootFactoryChannelFactory.php';
    }

    public static function tearDownAfterClass(): void
    {
        exec('rm -rf ' . escapeshellarg(self::$root));
    }

    #[Test]
    public function a_worker_scoped_consumer_receives_the_typed_factory(): void
    {
        $context = $this->context();
        $readonly = [
            BootFactoryMailChannel::class => new BootFactoryMailChannel(),
            BootFactorySmsChannel::class => new BootFactorySmsChannel(),
        ];
        (new GraphBuilder())->buildReadonlyGraph(
            [BootFactoryConsumer::class => BootFactoryConsumer::class],
            [],
            $context->injections,
            $readonly,
            static fn (string $id): ?string => class_exists($id) ? $id : null,
        );
        foreach ($readonly as $id => $instance) {
            $context->instanceStore->readonly[$id] = $instance;
        }

        (new FactoryBuildPhase())->execute($context);
        (new ValidationPhase())->execute($context);

        $consumer = $context->instanceStore->readonly[BootFactoryConsumer::class];
        self::assertInstanceOf(BootFactoryConsumer::class, $consumer);
        $factory = $consumer->channels();
        self::assertSame($readonly[BootFactoryMailChannel::class], $factory->getDefault());
        self::assertSame($readonly[BootFactorySmsChannel::class], $factory->get(BootFactoryChannelKind::Sms));
        self::assertSame([BootFactoryChannelKind::Mail, BootFactoryChannelKind::Sms], $factory->keys());
    }

    #[Test]
    public function an_execution_scoped_consumer_receives_the_typed_factory_resolving_execution_scoped_implementations_per_call(): void
    {
        $context = $this->context();
        $context->instanceStore->readonly[BootFactoryMailChannel::class] = new BootFactoryMailChannel();
        // The Sms implementation is execution-scoped: every get() resolves a fresh one.
        $context->instanceStore->prototypes[BootFactorySmsChannel::class] = new BootFactorySmsChannel();
        $store = $context->instanceStore;
        $context->resolveService = static fn (string $id): object => $store->readonly[$id] ?? clone $store->prototypes[$id];
        $idToClass = [];
        $prototypes = [];
        (new GraphBuilder())->buildExecutionScopedPrototypes(
            [BootFactoryConsumer::class => true],
            $context->injections,
            $context->instanceStore->readonly,
            $idToClass,
            $prototypes,
            static fn (string $id): ?string => class_exists($id) ? $id : null,
        );
        $context->instanceStore->prototypes[BootFactoryConsumer::class] = $prototypes[BootFactoryConsumer::class];
        $context->executionScopedClasses[BootFactoryConsumer::class] = true;
        $context->executionScopedClasses[BootFactorySmsChannel::class] = true;

        (new FactoryBuildPhase())->execute($context);
        (new ValidationPhase())->execute($context);

        $consumer = $context->instanceStore->prototypes[BootFactoryConsumer::class];
        self::assertInstanceOf(BootFactoryConsumer::class, $consumer);
        $factory = $consumer->channels();
        self::assertSame($context->instanceStore->readonly[BootFactoryMailChannel::class], $factory->getDefault());
        $sms = $factory->get(BootFactoryChannelKind::Sms);
        self::assertInstanceOf(BootFactorySmsChannel::class, $sms);
        self::assertNotSame($context->instanceStore->prototypes[BootFactorySmsChannel::class], $sms);
        self::assertNotSame($sms, $factory->get(BootFactoryChannelKind::Sms));
    }

    #[Test]
    public function generic_factory_typed_consumers_receive_the_generic_factory_next_to_a_typed_consumer(): void
    {
        $analyzer = (new \ReflectionClass(InjectionAnalyzer::class))->newInstanceWithoutConstructor();
        $context = $this->context();
        $context->injections = [
            BootFactoryConsumer::class => $analyzer->buildInjectionsForClass(BootFactoryConsumer::class),
            GenericBootFactoryConsumer::class => $analyzer->buildInjectionsForClass(GenericBootFactoryConsumer::class),
            GenericInterfaceBootFactoryConsumer::class => $analyzer->buildInjectionsForClass(GenericInterfaceBootFactoryConsumer::class),
        ];
        $readonly = [
            BootFactoryMailChannel::class => new BootFactoryMailChannel(),
            BootFactorySmsChannel::class => new BootFactorySmsChannel(),
        ];
        // Worker-scoped: the ContractFactory-typed consumer and the typed one.
        (new GraphBuilder())->buildReadonlyGraph(
            [
                GenericBootFactoryConsumer::class => GenericBootFactoryConsumer::class,
                BootFactoryConsumer::class => BootFactoryConsumer::class,
            ],
            [GenericInterfaceBootFactoryConsumer::class => true],
            $context->injections,
            $readonly,
            static fn (string $id): ?string => class_exists($id) ? $id : null,
        );
        foreach ($readonly as $id => $instance) {
            $context->instanceStore->readonly[$id] = $instance;
        }
        // Execution-scoped: the ContractFactoryInterface-typed consumer.
        $idToClass = [];
        $prototypes = [];
        (new GraphBuilder())->buildExecutionScopedPrototypes(
            [GenericInterfaceBootFactoryConsumer::class => true],
            $context->injections,
            $context->instanceStore->readonly,
            $idToClass,
            $prototypes,
            static fn (string $id): ?string => class_exists($id) ? $id : null,
        );
        $context->instanceStore->prototypes[GenericInterfaceBootFactoryConsumer::class] = $prototypes[GenericInterfaceBootFactoryConsumer::class];
        $context->executionScopedClasses[GenericInterfaceBootFactoryConsumer::class] = true;

        (new FactoryBuildPhase())->execute($context);
        (new ValidationPhase())->execute($context);

        $generic = $context->instanceStore->genericFactories[FactoryBootFactoryChannel::class];
        $worker = $context->instanceStore->readonly[GenericBootFactoryConsumer::class];
        self::assertInstanceOf(GenericBootFactoryConsumer::class, $worker);
        self::assertSame($generic, $worker->channels());
        self::assertSame($readonly[BootFactorySmsChannel::class], $worker->channels()->get(BootFactoryChannelKind::Sms));
        $scoped = $context->instanceStore->prototypes[GenericInterfaceBootFactoryConsumer::class];
        self::assertInstanceOf(GenericInterfaceBootFactoryConsumer::class, $scoped);
        self::assertSame($generic, $scoped->channels());
        self::assertSame($readonly[BootFactoryMailChannel::class], $scoped->channels()->getDefault());

        // The typed consumer, and the container's own lookup by Factory* key, get the typed factory.
        $typed = $context->instanceStore->readonly[BootFactoryConsumer::class];
        self::assertInstanceOf(BootFactoryConsumer::class, $typed);
        self::assertSame($context->instanceStore->factories[FactoryBootFactoryChannel::class], $typed->channels());
        self::assertNotInstanceOf(ContractFactory::class, $typed->channels());
    }

    #[Test]
    public function a_generic_factory_typed_property_without_a_contract_is_rejected(): void
    {
        $analyzer = (new \ReflectionClass(InjectionAnalyzer::class))->newInstanceWithoutConstructor();

        $this->expectException(InjectionException::class);
        $this->expectExceptionMessage('#[InjectAsFactory(of: YourContract::class)]');
        $analyzer->buildInjectionsForClass(GenericBootFactoryConsumerWithoutContract::class);
    }

    #[Test]
    public function a_missing_generated_factory_class_fails_boot_naming_the_generator_command(): void
    {
        $context = new BuildContext(new InstanceStore(), new TypeMap(), new InjectionMap());
        $context->injections = [
            UngeneratedFactoryConsumer::class => [
                'channels' => ['kind' => 'factory', 'type' => FactoryUngeneratedFactoryChannel::class, 'optional' => false],
            ],
        ];
        $context->contractDetails = [UngeneratedFactoryChannel::class => [
            'active' => UngeneratedMailChannel::class,
            'implementations' => [
                ['module' => 'A', 'class' => UngeneratedMailChannel::class, 'factoryKey' => BootFactoryChannelKind::Mail],
                ['module' => 'B', 'class' => UngeneratedSmsChannel::class, 'factoryKey' => BootFactoryChannelKind::Sms],
            ],
        ]];
        $store = $context->instanceStore;
        $store->readonly[UngeneratedMailChannel::class] = new UngeneratedMailChannel();
        $store->readonly[UngeneratedSmsChannel::class] = new UngeneratedSmsChannel();
        $store->readonly[UngeneratedFactoryConsumer::class] = new UngeneratedFactoryConsumer();
        $context->resolveService = static fn (string $id): object => $store->readonly[$id];

        $this->expectException(ContainerBuildException::class);
        $this->expectExceptionMessage(
            'the generated factory class App\\Registry\\Contracts\\UngeneratedFactoryChannelFactory implementing it is missing or out of date. '
            . 'Run `bin/semitexa registry:sync:contracts` to generate it.',
        );
        (new FactoryBuildPhase())->execute($context);
    }

    /**
     * @return array<class-string, array{active: class-string, implementations: list<array{module: string, class: class-string, factoryKey: BootFactoryChannelKind}>}>
     */
    private static function contractDetails(): array
    {
        return [BootFactoryChannel::class => [
            'active' => BootFactoryMailChannel::class,
            'implementations' => [
                ['module' => 'A', 'class' => BootFactoryMailChannel::class, 'factoryKey' => BootFactoryChannelKind::Mail],
                ['module' => 'B', 'class' => BootFactorySmsChannel::class, 'factoryKey' => BootFactoryChannelKind::Sms],
            ],
        ]];
    }

    private function context(): BuildContext
    {
        $context = new BuildContext(new InstanceStore(), new TypeMap(), new InjectionMap());
        $context->injections = [
            BootFactoryConsumer::class => [
                'channels' => ['kind' => 'factory', 'type' => FactoryBootFactoryChannel::class, 'optional' => false],
            ],
        ];
        $context->contractDetails = self::contractDetails();
        $store = $context->instanceStore;
        $context->resolveService = static fn (string $id): object => $store->readonly[$id];

        return $context;
    }
}
